---
title: "week06_b_quarto"
author: "Jake Reichard"
format: gfm
prefer-html: True
knitr: 
  opts_chunk: 
    fig.path: "../outputs/"
---

# Introductions

Today, we are learning about how to work with figures

## Load Libraries

```{r}
#| message: false
#| warning: false

library(tidyverse)
library(here)
library(palmerpenguins)
library(kableExtra)
```

## Make a Plot

```{r}
#| warning: false
#| out-width: "70%"
#| fig-align: "center"
#| label: fig-penguin
#| fig-cap: "This is a figure showing bill length by bill depth"

penguins %>% 
  ggplot(aes(x= bill_length_mm, y= bill_depth_mm, color= species))+
  geom_point()
```

When you look at @fig-penguin we can see there is a positive relationship between bill length and bill depth.

```{r}
#| warning: false
#| label: tbl-penguin
#| tbl-cap: "The mean bill length"

penguins %>% 
  group_by(species) %>% 
  summarise(bill_mean = mean(bill_length_mm, na.rm = T)) %>% 
  kbl() %>%  #make it a kable table
  kable_classic() %>% #adds a theme to table
  row_spec(2, bold = TRUE, color = "black", background = "lightgreen") %>%  #how to highlight a row and add color
  kable_styling(full_width = F) #doesn't make it too wide
```

The table @tbl-penguin has information on the mean bill lenght by speciecs.